# Generated by Django 4.2.5 on 2023-10-09 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('policy_compliance', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='compliance',
            options={'verbose_name_plural': 'Policy Compliances'},
        ),
    ]
