# Generated by Django 4.2.5 on 2023-09-22 01:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('billing_id', models.UUIDField(db_index=True, default=uuid.uuid5, primary_key=True, serialize=False)),
                ('billing_plan', models.CharField(choices=[('BASIC', 'Basic Plan'), ('STANDARD', 'Standard Plan'), ('PREMIUM', 'Premium Plan'), ('ENTERPRISE', 'Enterprise Plan'), ('CUSTOM', 'Custom Plan')], max_length=255)),
                ('auto_renew', models.BooleanField(default=True)),
                ('billing_period', models.DurationField()),
                ('payment_status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], max_length=255)),
                ('payment_method', models.CharField(choices=[('M_PESA', 'Mpesa'), ('DAZZLE_WALLET', 'Dazzle Wallet'), ('CO-OP_BANK_KENYA', 'Coop bank Kenya'), ('EQUITY_BANK_KENYA', 'Equity Bank Kenya'), ('PAYPAL', 'Paypal'), ('VISA_CARD', 'Visa Card'), ('MASTER_CARD', 'Master Card'), ('FLUTTERWAVE', 'Flutterwave')], max_length=255)),
                ('billing_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subscription_id', models.UUIDField(db_index=True, default=uuid.uuid5, primary_key=True, serialize=False)),
                ('subscription_plan', models.CharField(choices=[('ONE_TIME_USER', 'One-Time User'), ('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('YEARLY', 'Yearly'), ('CUSTOM_AND_UPGRADE', 'Custom and Upgrade')], max_length=255)),
            ],
            options={
                'ordering': ['-updated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice_id', models.UUIDField(db_index=True, default=uuid.uuid5, primary_key=True, serialize=False, unique=True)),
                ('invoice_date', models.DateField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('billing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing_services.billing')),
                ('invoice_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
                'abstract': False,
            },
        ),
    ]
