# Generated by Django 4.2.5 on 2023-10-09 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing_services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='billing_policy_text',
            field=models.TextField(default="\n## DazzleHR Billing Policy\nDazzleHR is a Software-as-a-Service (SaaS) HR system designed to streamline your organization's human resources management. This Billing Policy outlines the terms and conditions regarding subscription, billing, and payment for DazzleHR's services. By using DazzleHR, you agree to abide by this Billing Policy.\n\n### Subscription and Billing\n<!-- TODO: Do not accept if Scoll is not to the end -->\n1. Subscription Terms\nDazzleHR offers various subscription plans with different features and pricing. Subscribers may choose a plan that suits their organization's needs.\n\nSubscriptions are billed on a recurring basis (e.g., one-time purchaase, monthly, quarterly, or annually), depending on the chosen plan.\n\nYour subscription will automatically renew at the end of each billing period unless canceled. End of a free plan does not trigger auto bill, we let you activate that, an email will be triggered at the end of 14 days free trial.\n\n2. Payment\nSubscribers are required to provide valid payment information and agree to pay the subscription fees associated with their chosen plan.\n\nPayment methods accepted by DazzleHR include credit/debit cards or other forms as specified on our website.\n\n3. Billing Cycle\nThe billing cycle depends on the selected subscription plan and starts on the date of initial subscription activation.\n\nSubscribers will be billed in advance for their chosen billing period.\n\n4. Cancellation\nSubscribers can cancel their subscription at any time by visiting the Billing section on the DazzleHR platform.\n\nOnce canceled, the subscription will remain active until the end of the current billing period.\n\nDazzleHR does not provide refunds for any amounts already charged for subscription cancellation.\n\n5. Subscription Renewal\nDazzleHR automatically renews subscriptions at the end of each billing period unless canceled by the subscriber.\n\nRenewals are based on the originally chosen plan and payment method, unless updated by the subscriber.\n\nAccess and Termination\nDazzleHR reserves the right to deny access to any part of the service or terminate an organization's account, with or without notice, if it is found that the subscriber has violated the terms of this Billing Policy or DazzleHR's Terms of Service.\n\nTermination may occur without providing a refund or partial refund.\n\nContact Information\nIf you have any questions or concerns regarding this Billing Policy, please contact our billing team at billing@dazzlehr.com.\n\nPlease make sure to adapt this policy to your specific terms and conditions, and ensure that it complies with any legal or regulatory requirements in your jurisdiction. Additionally, you may want to include information on pricing, available subscription plans, and payment methods on your website or within the policy itself.\n"),
        ),
    ]
