# Generated by Django 4.2.5 on 2023-09-23 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing_services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='billing_id',
            field=models.UUIDField(db_index=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_id',
            field=models.UUIDField(db_index=True, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='subscription_id',
            field=models.UUIDField(db_index=True, primary_key=True, serialize=False),
        ),
    ]
