# Generated by Django 4.2.5 on 2023-09-22 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_service', '0002_alter_customuser_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField()),
                ('img_url', models.URLField()),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('BASIC', 'Basic Role'), ('EMPLOYEE', 'Employee'), ('SUPERVISOR', 'Supervisor'), ('SALES', 'Sales'), ('MARKETING', 'Marketing'), ('ENGINEERING', 'Engineering'), ('MANAGER', 'Manager'), ('HR_MANAGER', 'HR Manager')], default='BASIC', max_length=255),
        ),
    ]
