# Generated by Django 4.2.5 on 2023-09-23 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, default=None, null=True, verbose_name='IP address'),
        ),
    ]
